### ISSUE TITLE
Problem with `run_rtwig` on erroneous Treegraph QSMs: `Column `id` doesn't exist`

### ISSUE THREAD

**Issue by thomashay** [aidanmorales/rTwig#15]
Hello again, I encountered once again an issue when running `run_rtwig` on some of my treegraph QSMs. I updated the package yesterday to the newest version because I need the added ability of working with filtered cylinder data, which is great by the way! The problem is that I cannot `run_rtwig` on some certain Treegraph QSMs. I noted that only QSMs which have errors in the form of branches being located below the lowest stem part are affected (see the picture below). This issue did not exist in the rTwig version I used before. I get the error:
```
...
Filtering Paths
Modeling Paths
Processed 1265 groups out of 1265. 100% done. Time elapsed: 6s. ETA: 0s.
Updating Radii
Building Cylinder Network
Error in `tidyselect_locs()`:
! Can't select columns that don't exist.
✖ Column `id` doesn't exist.
```
![image](https://github.com/user-attachments/assets/2d72d2d4-42f4-4728-b933-1df6931452c8)

As with other issues I encountered previously, I can run `update_cylinders`, `correct_radii`, `standardize_qsm`, and `tree_metrics` individually on this problematic QSM. You can find it here if you want to test yourself: https://owncloud.gwdg.de/index.php/s/xdZnOQPG5LJZmGD

Best regards!

**Comment by aidanmorales** [comment]
Hi again @thomashay,

Thanks for letting me know about these issues and providing example data and the error outputs. It makes debugging much easier!

It looks like this issue was caused by the new QSM connectivity verification introduced in v1.3.0. This would be triggered by QSMs with poor topology, like you suspected. The verification code was too high a level inside the `tree_metrics()` function, so the variable names would throw an error if not standardized. This should be fixed now in the latest development version, including a some more small bugs I found while tackling this issue. Please try out the latest dev version and let me know how it goes. Thanks!

**Comment by thomashay** [comment]
Works perfectly now, thanks again for the amazing support!
