### ISSUE TITLE
Tree metrics for disconnected structures?

### ISSUE THREAD

**Issue by thomashay** [aidanmorales/rTwig#16]
Hello again,
this time I would like to discuss a bit more of a general question. In my workflow, I am analyzing QSMs derived from relatively low-quality point clouds, which therefore contain quite some (in parts drastic) errors. My goal is to derive detailed architectural characteristics of the trees in order to combine data from several trees into one "average" modelled tree implemented in a different software platform. To basically reduce the noise in the QSM data, I am filtering the cylinders with what you could call knowledge-informed botanical filters (e.g. stem segments cannot have an zenith angle larger than x, ect.). This of course results in disconnected cylinder structures (see picture). Right now, rTwig cannot calculate tree metrics for such structures (or can it?). I understand that not all metrics might be valid for such structures, but others could be. For example, I would be interested in the stem taper data. I think I can derive the things I am interested in from the filtered cylinder data myself, but it feels a bit like reimplementing what the package can do anyways. I get that disconnected structures break some of the core concepts of rTwig, but I am interested to hear your thoughts on this! I think that rTwig provides an excellent room for working with QSMs in R in general, and I would like to avoid leaving this room with some custom analysis functions as much as possible. 

Best regards!

![image](https://github.com/user-attachments/assets/88f9dad4-b894-4ee7-87fa-b37add902dd2)

**Comment by aidanmorales** [comment]
Hi @thomashay,

Right now, rTwig is designed to correct the overestimation in small branches and twigs from technical limitations in remote sensing instruments (e.g. beam size, diameter, divergence, etc.) and calculate detailed metrics. The main assumption is that the underlying QSM has a good topological structure. In that regard, rTwig filters out "unrealistic" cylinders, before doing the path tapering.  These modified cylinders can be seen in the 'modified' column, where a 0 was never modified, and a 1 was modified across all paths. rTwig also does validation and correction to make sure the parent-child relationships are valid, but works within the constraints of the input QSM's topology. The rule of thumb is that if the QSM closely resembles the real tree, it is a good model. Conversely, if the QSM is not visually realistic, it is not a good QSM, and any metrics should be treated with care. 

So, I understand that you want to average tree metrics across different QSM software, which is very valid and encouraged. However, I am not quite sure what you want to do that rTwig can not already do? It sounds like the input QSMs are the problem here. If you want main stem tapers, you can just pass the filtered main stem data (branch 1, or branch order 0) to `tree_metrics()`. The same goes for individual branches. If you want a simple summary on disconnected data (e.g. the results from pruning), the `qsm_summary()` function will work, but I suspect that you want the more detailed metrics?

If there are specific things you would like rTwig to do, I would be happy to look into it. However, I need specific examples and data to implement these new features for use by everyone. These could either be additions to existing functions, or new ones entirely. I hope this makes sense. I appreciate your use of the package, and welcome any suggestions that could improve its functionality. Thanks!

**Comment by thomashay** [comment]
Thanks for your detailed answer @aidanmorales and the clarifications! I think what maybe did not come across is that I am not pruning my QSMs in the sense of e.g. the `prune_qsm` function, I am just throwing out some of the cylinders irrespective of topology. This is what I mean with "disconnected structures" and why I cannot pass the filtered data to `tree_metrics`, this throws an error. I attached an example script and QSM in .RData format so you can see what I mean. This QSM is one of the poorest I have. 

You are right that metrics based on such low-quality data should be treated with care, but I think it is not uncommon to encounter such data. Also, especially for TreeQSM, I found that you regularly receive QSMs which are at least geometrically disconnected in places (The .RData qsm I am attaching is an example of this). Therefore, I think what I am doing is conceptually not far removed from just working with low-quality QSMs from the beginning.

Best regards!
[filter_example.zip](https://github.com/user-attachments/files/18113661/filter_example.zip)

**Comment by aidanmorales** [comment]
@thomashay 

Thanks for the examples. I see what you are trying to do now. I'll look into adding a boolean function parameter to bypass the connectivity checks. It shouldn't be a problem, but I will warn the user about the potential issues of doing this.

**Comment by thomashay** [comment]
Thanks for the offer @aidanmorales ! I am looking forward to it!

**Comment by aidanmorales** [comment]
@thomashay: I added a new parameter to `tree_metrics()` called `verify`. Please try this out in the latest development version and let me know if this is what you had in mind.

**Comment by thomashay** [comment]
@aidanmorales Very nice, this is what I imagined! One question on the branch data from tree_metrics: I guess it "inherits" the topology from the original QSM when generated for disconnected structures? Or how are the parent-child relationships defined? Best regards and thanks again for the great work!

**Comment by aidanmorales** [comment]
@thomashay, the initial parent-child relationships are defined by the QSM software (TreeQSM, SimpleForest, Treegraph, etc.). rTwig just corrects any topological errors and standardizes the cylinder relationships in the QSM in `update_cylinders()`, ensuring all of the functions work together. This topology is then passed to `tree_metrics()`. In v.1.3.0, I added strict topology checks, which check for disconnected structures, and only allow structures that are a 'whole tree' to run. Without these checks, there can be multiple NA values caused by missing parent-child relationships. The actual network is built using `igraph`, and implemented in `rTwig:::build_network()`. 

So, to answer your question, yes. If a parent or child cylinder id is missing, anything that relies on it will be NA, such as branch angles, zenith, azimuth, etc. Volumes and surface area will also be incorrect. That is why I put the check in place to begin with. Again, the topology is only as good as the input QSM. If you are willing to accept missing values, `verify = false` just bypasses any checks, and is only needed for disconnected structures. The output will be the same if passing in a connected structure. 

The core functionality of rTwig won't be changing anytime soon for compatibility reasons, but if you have any new feature requests like this in the future, I'll take a look at implementing them. Thanks.
