### ISSUE TITLE
Problem with `standardize_qsm` and `tree_metrics` for SimpleForest QSM: `distanceFromBase` doesn't exist

### ISSUE THREAD

**Issue by thomashay** [aidanmorales/rTwig#4]
Hello, 
thanks for your nice package, I find it very helpful and nice to use.
I am having an issue running `standardize_qsm()` and  `tree_metrics()` on my SimpleForest QSM. I get the error:

```
Error in `tidyselect_locs()`:
! Can't select columns that don't exist.
✖ Column `distanceFromBase` doesn't exist.
```

In fact, this column does not exist in my QSM. I am running SimpleForest 5.3.2 in Computree 5.0.221b (The normal Windows executable Download version from https://www.simpleforest.org/pages/download.html) and rTwig 1.1.0.

Any ideas on this? 

I attached one of my QSMs in case you want to see for yourself.

Best regards!
[qsm.csv](https://github.com/user-attachments/files/17045336/qsm.csv)

**Comment by aidanmorales** [comment]
Hi @thomashay,

Thanks for the bug report and QSM to test. 

I pushed a commit (2e483df) to the development version (v1.1.0.9000) that should fix your issue. Please test with the latest development version from GitHub and let me know how it goes. See install code below. Unfortunately, this bug will affect all current users of SimpleForest until this fix gets pushed to CRAN. In the meantime, renaming `distanceToTwig` to `distanceToTwigSF` before running `update_cylinders()` will fix this. 

The issue is that new versions of SimpleForest calculate `distanceToTwig`, but not `distanceToBase`. rTwig calculates `distanceToTwig` and `distanceToBase` in the same function. The SimpleForest QSM in the package is missing `distanceToTwig`, so the code ran fine, but if `distanceToTwig` already exists, it would skip its calculation causing it to be missing. 

The new fix renames the existing `distanceToTwig` to `distanceToTwigSF` , and then calculates the new `distanceToTwig` and `distanceToBase`.  On a side note, it looks like SimpleForest uses the maximum distance to a twig, while rTwig use the average distance to all supported twigs, from any given cylinder. I might add the max distance to a twig as a new output in a future update if enough people find it useful. 

```r{}
# install.packages("devtools")
devtools::install_github("aidanmorales/rTwig")
```

**Comment by thomashay** [comment]
Thanks for the extremely fast reply and fix! Works perfectly for me now! I can't say right now if the max distance to a twig could also be useful for me, but I guess it doesn't hurt to have it :)
